library("RandomWalkRestartMH")
library("igraph")
# setwd("C:/users/USER/Desktop/agneet/Controlled/Controlled/Run1")
data1 = read.csv("C:/Users/USER/Desktop/agneet/Diseased/Diseased/Diseased_Results/layer1/by8/layer1_unweighted_v8_final.csv",header=FALSE)
data2 = read.csv("C:/Users/USER/Desktop/agneet/Diseased/Diseased/Diseased_Results/layer2/layer2_unweighted.csv",header=FALSE)
m1=as.matrix(data1)
m2=as.matrix(data2)
g1=graph.data.frame(m1,directed=FALSE)
g2=graph.data.frame(m2,directed=FALSE)
multiObject <- create.multiplex(g1,g2,Layers_Name=c("PCC","Semantic"))
AdjMatrix <- compute.adjacency.matrix(multiObject,delta = 0.7)
AdjMatrixNorm <- normalize.multiplex.adjacency(AdjMatrix)
seedGenes<-scan("C:/Users/USER/Desktop/agneet/Diseased/Diseased/Diseased_Results/seeds/seed_8.txt", what="", sep="\n")
RWR_Results <- Random.Walk.Restart.Multiplex(AdjMatrixNorm,multiObject,seedGenes)
RWR_Results
TopResults_40 <-create.multiplexNetwork.topResults(RWR_Results,multiObject,k=40)
par(mar=c(0.1,0.1,0.1,0.1))
plot(TopResults_40, vertex.label.color="black",vertex.frame.color="#ffffff", vertex.size= 20,edge.curved= ifelse(E(TopResults_40)$type == "PCC",0.4,0),edge.width=0.8,edge.color=ifelse(E(TopResults_40)$type == "PCC",
                         "blue","yellow"))
